### ISSUE TITLE
Open results and trained models

### ISSUE THREAD

**Issue by qifengluo** [JZhao12/CVML-Pose#1]
Hi,  We need to conduct comparative experiments with methods like AAE.  Can you publicly disclose the trained model or send me a copy of the pose results from the LM and LMO datasets.

**Comment by JZhao12** [comment]
Hi,

We have opened our results here: https://github.com/JZhao12/CVML-Pose#17-trained-models-and-results

I'm very sorry for not providing trained models (network weights) due to the licenses of the datasets, but as they are publicly available, you can always train the models following the guidance of our method. Sorry for any inconvenience.

Best,
Jianyu
